const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix
	.styles(
        [
            'node_modules/admin-lte/plugins/fontawesome-free/css/all.min.css',
            'node_modules/admin-lte/dist/css/adminlte.min.css',
            'node_modules/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.css',
            'node_modules/admin-lte/plugins/select2/css/select2.min.css',
            'node_modules/admin-lte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css',
            'resources/css/admin.css',
        ],
        'public/css/admin.min.css'
    )
    .scripts(
        [
            'node_modules/admin-lte/plugins/jquery/jquery.min.js',
            'node_modules/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js',
            'node_modules/admin-lte/plugins/datatables/jquery.dataTables.js',
            'node_modules/admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.js',
            'node_modules/admin-lte/plugins/bs-custom-file-input/bs-custom-file-input.min.js',
            'node_modules/admin-lte/plugins/select2/js/select2.full.min.js',
            'node_modules/admin-lte/dist/js/adminlte.min.js',
            'node_modules/admin-lte/dist/js/demo.js',
        ],
        'public/js/admin.min.js'
    )
	.styles(
        [
            'node_modules/admin-lte/plugins/fontawesome-free/css/all.min.css',
            'node_modules/admin-lte/dist/css/adminlte.min.css',
            'node_modules/animate.css/animate.min.css',
            'resources/css/owl.carousel.min.css',
            'resources/css/app.css',
            'resources/css/style.css',
        ],
        'public/css/front.min.css'
    )
    .scripts(
        [
            'node_modules/admin-lte/plugins/jquery/jquery.min.js',
            'node_modules/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js',
            'node_modules/admin-lte/dist/js/adminlte.min.js',
            'node_modules/wow.js/dist/wow.min.js',
            'node_modules/admin-lte/dist/js/demo.js',
        ],
        'public/js/front.min.js'
    )
    .scripts(
        [
            'resources/js/script.js',
        ],
        'public/js/script.min.js'
    )
    .scripts(
        [
            'resources/js/theme.js',
        ],
        'public/js/theme.min.js'
    )
    .scripts(
        [
            'app-assets/vendors/js/vendors.min.js',
            'app-assets/js/core/app-menu.js',
            'app-assets/js/core/app.js',
            'app-assets/js/scripts/components.js',
        ],
        'public/js/authentication.min.js'
    )
    .styles(
        [
            'app-assets/vendors/css/vendors.min.css',
            'app-assets/css/bootstrap.css',
            'app-assets/css/bootstrap-extended.css',
            'app-assets/css/colors.css',
            'app-assets/css/components.css',
            'app-assets/css/themes/dark-layout.css',
            'app-assets/css/themes/semi-dark-layout.css',
            'app-assets/css/core/menu/menu-types/vertical-menu.css',
            'app-assets/css/core/colors/palette-gradient.css',
            'app-assets/css/pages/authentication.css',
            'resources/css/authentication.css',
        ],
        'public/css/authentication.min.css'
    )
    .scripts(
        [
            'resources/js/filereader.js',
        ],
        'public/js/filereader.min.js'
    )
	.copyDirectory(
		[
			'node_modules/admin-lte/plugins/fontawesome-free/webfonts',
            'app-assets/fonts/feather/fonts'
		],
		'public/webfonts'
	);
